### ISSUE TITLE
using WriteTNTcharacters() with continuous matrix

### ISSUE THREAD

**Issue by jc17659** [ms609/TreeTools#139]
I tried to export a TNT version of a continuous phylogenetic matrix using this function but the resultant characters aren't separated by anything so TNT doesn't interpret them correctly.

Here is an example of what the output looks like (68 continuous characters in this taxa):

`taxa_a 1.7380.9960.1270.1570.5240.3030.880.1860.0890.8420.1030.0510.8820.1230.0570.7780.0020.0460.7380.0110.1230.8350.2220.0320.3380.5290.5730.5750.030.4470.3160.6020.5110.231.8180.9950.0970.130.4340.1590.94100.0970.8270.1760.2390.8270.2110.330.7890.2960.3270.7510.4250.2780.8810.1880.2670.3660.4450.5980.36800.4850.3050.6340.5080.271`

I tried initially reading the dataset in using ReadCharacters() as well as using as.matrix() before using WriteTNTCharacters() to no avail. Both these methods read in the characters correctly. Hope I didn't miss a simple fix

J

**Comment by ms609** [comment]
Hopefully then the fix is as simple as including a space between the written characters, which I've just implemented – could you try installing the devel version with `devtools::install_github("ms609/TreeTools")` and see whether things behave as you expect?

**Comment by jc17659** [comment]
perfect - just checked it and the continuous characters now read correctly into TNT

cheers!

**Comment by ms609** [comment]
Super, great to hear!  Do let me know if you run into any further complications.  Meanwhile, I'll submit the updated code to CRAN.
