### ISSUE TITLE
Custom directory for caching

### ISSUE THREAD

**Issue by stitam** [ms609/TreeTools#140]
I want to use TreeTools inside a docker (singularity, in fact) container and it seems TreeTools uses `/home` for caching  results which is a bottleneck in my application. It would be better if 1. I could tell TreeTools not to use a cache directory at all or 2. I could set the cache directory manually to be an arbitrary directory. Is this possible with TreeTools at the moment? If not, would this be relatively simple to implement? Many thanks.

**Comment by ms609** [comment]
Thanks for the question.  I suspect the answer will be to modify the cache settings of the  R.cache package.  I'll look into whether there's a straightforward way to do so!

**Comment by stitam** [comment]
I found an approach that works. More background on the issue: when I run my analysis with Singularity I have to use `--no-home` option to prevent Singularity from looking for R packages in my host system (would defeat the purpose of a container) but then R.cache cannot create and populate the `~/.cache/R/R.cache` directory. A potential solution is to tell Singularity not to use my home in general BUT bind my working directory as my home using the `--no-home --bind <workdir>:$HOME` option. This way if any tools want to create anything in my home they will create it in the working directory instead.

Alternatively, `R.cache::setCacheRootPath()` could be used to set a cache path for R.cache but I couldn't get it to work properly; it seems when I load R.cache it looks for the non-existing path and then fails with an error before I get a change to set another path.

Since this issue only comes up when using containers and can be solved from the container side, I think it can be closed.

**Comment by ms609** [comment]
Thanks for following up on this, and glad to hear that you were able to find a solution.
