### ISSUE TITLE
Will not install on Rstudio

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ms609/TreeTools#143]
*** arch - i386
/mingw32/bin/g++  -std=gnu++17 -I"C:/Users/THEODO~1.ALL/R-41~1.1/include" -DNDEBUG  -I'C:/Users/Theodore.Allnutt/Rlibs/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ClusterTable.cpp -o ClusterTable.o
In file included from ClusterTable.cpp:1:
../inst/include/TreeTools/ClusterTable.h:6:10: fatal error: Rcpp/Lightest: No such file or directory
 #include <Rcpp/Lightest>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [C:/Users/THEODO~1.ALL/R-41~1.1/etc/i386/Makeconf:245: ClusterTable.o] Error 1
ERROR: compilation failed for package 'TreeTools'
* removing 'C:/Users/Theodore.Allnutt/Rlibs/TreeTools'
Warning in install.packages :
  installation of package ‘TreeTools’ had non-zero exit status

**Comment by theo-allnutt-bioinformatics** [comment]
Installed through package manager ok.

**Comment by ms609** [comment]
You possibly needed to update Rcpp.  Glad you got it working.
