### ISSUE TITLE
DropTip will not remove tip on tree

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [ms609/TreeTools#144]
I cannot get DropTip to remove a tip. What am I doing wrong? Tried with several trees. Here is an example:

```
library(phytools)
library(ggtree)
library(TreeTools)

tree2<-pbtree(n=5)
plotTree(tree2)
DropTip(tree2,'t4',preorder = TRUE,check=TRUE)
plotTree(tree2)
```
The tree does not change.

Thanks.

**Comment by ms609** [comment]
You are not assigning the modified tree to tree2.
Try `tree2 <- DropTip(tree2, 't4')`

**Comment by theo-allnutt-bioinformatics** [comment]
doh!
