### ISSUE TITLE
If tree has defined node.labels AddTips() will not change them

### ISSUE THREAD

**Issue by stitam** [ms609/TreeTools#149]
Hi,

I'm not sure if I'm using `AddTips()` incorrectly or there is an issue with the function. Reprex below:

``` r
# create a random tree
set.seed(0)
tree <- ape::rtree(10)
# define node labels and plot
tree$node.label <- paste0("Node_", 1:tree$Nnode)
plot(tree, show.node.label = TRUE)
```

![](https://i.imgur.com/x4bTE9s.png)

``` r
# add a tip
tree2 <- TreeTools::AddTip(tree, where = "t8", label = "new", edgeLength = 0)
# plot, notice that: 1. internal node labels change, 2. "Node_1" is now recycled!
plot(tree2, show.node.label = TRUE)
```

![](https://i.imgur.com/3u8eV9L.png)

``` r
# Also node.label does not change
tree2$node.label
#> [1] "Node_1" "Node_2" "Node_3" "Node_4" "Node_5" "Node_6" "Node_7" "Node_8"
#> [9] "Node_9"
```

<sup>Created on 2024-03-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

This is a problem because tools that make use of the `node.label` element will produce all sorts of issues downstream.

Not sure this is a proper fix but adding something like this may work:

```
if ("node.label" %in% names(tree) {
  tree$node.label <- paste0("Node_",  1:tree$Nnode)
}
```

The names of the internal nodes will still change but the redundancy will be eliminated.

**Comment by ms609** [comment]
Thanks for the report; `AddTip()` is not currently set up to support node labels, but I can take a look at this.
