### ISSUE TITLE
TCIContext(tree)$maximum overflow

### ISSUE THREAD

**Issue by RussellGarwood** [ms609/TreeTools#158]
Hi @ms609 - I'm implementing tci using TreeTools v1.11.1 as per this issue

https://github.com/palaeoware/trevosim/issues/6

The file in the TREvoSim repository folder /comparison_to_empirical_data/Empirical_data/Echinoidea.tre (attached as a zip) throws an error when calculating TCIContext(tree)$maximum - it looks like an overflow:

Error in DoubleFactorial((x + x) - 2L) :   301!! is too large to represent. Use LnDoubleFactorial() instead.

This has 164 leaves, so it is not a massive tree, and I'm wondering if something other than size could be causing this issue.

[Echinoidea.zip](https://github.com/user-attachments/files/15899465/Echinoidea.zip)

**Comment by ms609** [comment]
Thanks for the report – this is fixed in #159, which I'll merge once tests are passed.

(I've a half-written reply to your question at https://github.com/palaeoware/trevosim/issues/6 on my other computer, which I'll try to complete tonight!)

**Comment by ms609** [comment]
Should now be available via `devtools::install_github("ms609/TreeTools")`

**Comment by RussellGarwood** [comment]
Thanks for the rapid fix, @m609! And also for the answer to my question forthcoming - I've implemented this metric and the results are broadly the same, but am still interested in whether this is referable to Colless!
