### ISSUE TITLE
Error parsing Nexus file

### ISSUE THREAD

**Issue by jc17659** [ms609/TreeTools#26]
Hi there Martin,

Just trying to using ReadCharacters to read in a continuous dataset I am analysing in various ways.

Unfortunately the continuous decimals are parsed in individually as characters, eg 0.15 would be read in as '0' '.' '1' '5'

I had a a look at the github files and couldn't see any mention of continuous characters, though I may have missed that part. Is there a way to read them in at all?

I have attached the dataset in case that is of any use, but had to convert it to .txt instead of .nex
[koch_raw_MASTER.txt](https://github.com/ms609/TreeTools/files/4668508/koch_raw_MASTER.txt)

Thanks for your time

**Comment by ms609** [comment]
Thanks for the report.  I've added support for continuous characters on the development branch.
To access, use:

`install_github('ms609/TreeTools', ref='v1.0.0')`

**Comment by jc17659** [comment]
No problem and cheers for getting back to me so quickly, was not expecting to able to get this sorted today!

I'm going to be working with continuous data lots in the future so this is v v useful

trying to install it also made me confront a recurring issue I've been having with how Xcode was working on my mac, which I have now found a solution for so doubly thanks!

It now reads in perfectly
