### ISSUE TITLE
Format of the tree?

### ISSUE THREAD

**Issue by marwa38** [ms609/TreeTools#88]
Hello 

Do you provide a function to know what is the format of the tree I created?
I used the method here: https://f1000research.com/articles/5-1492
Does saving the tree in .rds change the tree format?
.txt would make it NEWICK 
Cheers

**Comment by ms609** [comment]
Use `class(object)` to see how an object is represented within R.  You can use write.nexus to write a tree to a text file in NEXUS format, or write.tree to write it in NEWICK format.

Sorry if I've misunderstood the question...

**Comment by marwa38** [comment]
thanks very much Martin @ms609 that is helpful
